import './globals.css';

import { Inter } from '@next/font/google';
import { Counter } from '../components/counter/Counter';
const inter = Inter();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <title>Jesse Winton – Storyteller & Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <header className="container py-2 flex justify-between">
          Application
          <Counter />
        </header>
        <main className="min-h-screen flex flex-col flex-1">{children}</main>
      </body>
    </html>
  );
}
